recovery: dc: dc2: fixed exception on container load
On alpha tests we've got an error:
    TypeError: __init__() got an unexpected keyword argument 'is_sorted'

Bug was introduced in:
    "recovery: renamed collisions with python builtins"

Pointy hat to: me